/**
 * generate-gallery.js
 *
 * Scans your images folder and writes gallery-data.js automatically.
 * Run once (or any time you add/remove photos):
 *
 *   node generate-gallery.js
 *
 * That's it. Refresh the page and all photos appear.
 */

const fs   = require('fs');
const path = require('path');

/* ── Config ──────────────────────────────────────────────── */
const IMAGES_DIR  = './images';          // folder to scan
const OUTPUT_FILE = './gallery-data.js'; // generated file (don't edit manually)
const EXTENSIONS  = ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.avif'];
/* ────────────────────────────────────────────────────────── */

function captionFromFilename(name) {
    return name
        .replace(/\.[^.]+$/, '')
        .replace(/[-_]+/g, ' ')
        .replace(/\b\w/g, c => c.toUpperCase())
        .trim();
}

// Make sure images folder exists
if (!fs.existsSync(IMAGES_DIR)) {
    fs.mkdirSync(IMAGES_DIR, { recursive: true });
    console.log(`📁  Created "${IMAGES_DIR}" folder — drop your photos in there, then run this script again.`);
    process.exit(0);
}

// Scan recursively (supports sub-folders)
function scanDir(dir, base = IMAGES_DIR) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    const images  = [];
    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            images.push(...scanDir(fullPath, base));
        } else if (EXTENSIONS.includes(path.extname(entry.name).toLowerCase())) {
            const rel     = path.relative(base, fullPath).replace(/\\/g, '/');
            const caption = captionFromFilename(path.basename(entry.name));
            images.push({ src: `images/${rel}`, caption });
        }
    }
    return images;
}

const images = scanDir(IMAGES_DIR);

if (!images.length) {
    console.log(`⚠️  No images found in "${IMAGES_DIR}". Drop some photos in and run again.`);
    process.exit(0);
}

// Write gallery-data.js
const output = `/* AUTO-GENERATED by generate-gallery.js — do not edit by hand */
/* Last updated: ${new Date().toLocaleString()} */
/* ${images.length} photo${images.length !== 1 ? 's' : ''} found */

window.GALLERY_DATA = ${JSON.stringify(images, null, 2)};
`;

fs.writeFileSync(OUTPUT_FILE, output, 'utf8');

console.log(`✅  Done! ${images.length} photo${images.length !== 1 ? 's' : ''} found → "${OUTPUT_FILE}" written.`);
console.log('    Refresh the page and they\'ll all appear. 🌙');
images.forEach(img => console.log(`    · ${img.src}  (${img.caption})`));