# generate-gallery.ps1
# Run from your tofu-website folder: .\generate-gallery.ps1

$imagesDir  = ".\images"
$outputFile = ".\gallery-data.js"
$extensions = @(".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif")

if (-not (Test-Path $imagesDir)) {
    New-Item -ItemType Directory -Path $imagesDir | Out-Null
    Write-Host "Created images/ folder. Drop your photos in, then run this script again."
    exit
}

$files = Get-ChildItem -Path $imagesDir -Recurse -File |
    Where-Object { $extensions -contains $_.Extension.ToLower() }

if ($files.Count -eq 0) {
    Write-Host "No images found in images/. Drop some photos in and run again."
    exit
}

function CaptionFromFilename($name) {
    $name = [System.IO.Path]::GetFileNameWithoutExtension($name)
    $name = $name -replace '[-_]+', ' '
    $name = $name -replace '^\s*\d{4,}\s*', ''
    if ($name.Trim() -eq '') { $name = 'Memory' }
    $words = $name.Trim().Split(' ') | ForEach-Object {
        if ($_.Length -gt 0) { $_.Substring(0,1).ToUpper() + $_.Substring(1).ToLower() }
    }
    return ($words -join ' ').Trim()
}

$resolvedBase = (Resolve-Path $imagesDir).Path

$entries = @()
foreach ($file in $files) {
    $rel     = $file.FullName.Replace($resolvedBase + "\", "").Replace("\", "/")
    $caption = CaptionFromFilename($file.Name)
    $caption = $caption -replace '"', '\"'
    $entries += "  { ""src"": ""images/$rel"", ""caption"": ""$caption"" }"
}

$date  = Get-Date -Format "dd/MM/yyyy HH:mm:ss"
$count = $files.Count
$json  = $entries -join ",`n"

$lines = @()
$lines += "/* AUTO-GENERATED by generate-gallery.ps1 */"
$lines += "/* Last updated: $date - $count photos */"
$lines += ""
$lines += "window.GALLERY_DATA = ["
$lines += $json
$lines += "];"

$outputPath = Join-Path (Get-Location) "gallery-data.js"
[System.IO.File]::WriteAllLines(
    $outputPath,
    $lines,
    [System.Text.UTF8Encoding]::new($false)
)

Write-Host ""
Write-Host "Done! $count photos written to gallery-data.js"
Write-Host "Refresh the page and they will all appear."
Write-Host ""
foreach ($file in $files) {
    $rel = $file.FullName.Replace($resolvedBase + "\", "").Replace("\", "/")
    Write-Host "  . images/$rel"
}