# generate-gallery.ps1
# Scans the images/ folder and writes gallery-data.js
# Run from the tofu-website folder:
#   .\generate-gallery.ps1

$imagesDir  = ".\images"
$outputFile = ".\gallery-data.js"
$extensions = @(".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif")

# Create images folder if it doesn't exist
if (-not (Test-Path $imagesDir)) {
    New-Item -ItemType Directory -Path $imagesDir | Out-Null
    Write-Host "Created images/ folder. Drop your photos in, then run this script again."
    exit
}

# Find all image files recursively
$files = Get-ChildItem -Path $imagesDir -Recurse -File |
    Where-Object { $extensions -contains $_.Extension.ToLower() }

if ($files.Count -eq 0) {
    Write-Host "No images found in images/. Drop some photos in and run again."
    exit
}

# Build the gallery array
function CaptionFromFilename($name) {
    $name = [System.IO.Path]::GetFileNameWithoutExtension($name)
    $name = $name -replace '[-_]+', ' '
    $words = $name.Split(' ') | ForEach-Object {
        if ($_.Length -gt 0) { $_.Substring(0,1).ToUpper() + $_.Substring(1).ToLower() }
    }
    return ($words -join ' ').Trim()
}

$entries = @()
foreach ($file in $files) {
    $rel     = $file.FullName.Replace((Resolve-Path $imagesDir).Path + "\", "").Replace("\", "/")
    $caption = CaptionFromFilename($file.Name)
    $entries += "  { `"src`": `"images/$rel`", `"caption`": `"$caption`" }"
}

$date    = Get-Date -Format "dd/MM/yyyy HH:mm:ss"
$count   = $files.Count
$json    = $entries -join ",`n"

$output = @"
/* AUTO-GENERATED by generate-gallery.ps1 — do not edit by hand */
/* Last updated: $date */
/* $count photo$(if ($count -ne 1) { 's' }) found */

window.GALLERY_DATA = [
$json
];
"@

Set-Content -Path $outputFile -Value $output -Encoding UTF8

Write-Host ""
Write-Host "Done! $count photo$(if ($count -ne 1) { 's' }) found -> gallery-data.js written."
Write-Host "Refresh the page and they'll all appear."
Write-Host ""
foreach ($file in $files) {
    $rel = $file.FullName.Replace((Resolve-Path $imagesDir).Path + "\", "").Replace("\", "/")
    Write-Host "  . images/$rel"
}